# coding: utf-8
# author     Yuichi Yasuda @ quattro corporate design
# copyright  quattro corporate design. All right reserved.


import weapy.weafile as ea
import weapy.epwfile as epw
import pandas as pd

if(__name__ == '__main__'):

    """例）拡張アメダス標準年のデータからTRNSYS,Type99形式のファイルを出力する
    """

    # 拡張アメダス気象データ
    # --------------------------------
    no = 363 #東京
    weafile = r'c:\AMeDAS\RWY8195.wea' #1995年版
    wea = ea.WeaFile(weafile, no)

    print(wea.ambient_temperatures)
    print(wea.relative_humidities)
    
    # DataFrameを生成する
    df = pd.DataFrame(
        {
        'TAMB': wea.ambient_temperatures,
        'RHUM': wea.relative_humidities,
        'IGLOB_H': wea.horizontal_global_solar_irradiations,
        'udef1': wea.downward_longwave_irradiations,
        'WDIR': wea.wind_directions,
        'WSPEED': wea.wind_velocities,
        'udef2': wea.precipitation_amounts,
        'udef3': wea.sunshine_durations,
        })

    df = df.round({'TAMB':1, 'RHUM':3, 'IGLOB_H':3, 'udef1':3, 'WDIR':1, 'WSPEED':1, 'udef2':1, 'udef3':1})
    pd.options.display.float_format = '{:.4g}'.format

    print(df)

    #ファイル名
    fname = 'ea_{:0=3}.99'.format(no)
    #Type99 のヘッダー（拡張アメダス気象データ、東京）
    t99header = [
            '<userdefined>       ! This weather data is generated by ExtAmedas plugin.',
            '<longitude> -139.76 ! The original data is \'Expanded AMeDAS Weather Data\' issued by AIJ in Japan.',
            '<latitude>  35.69   ! If you have a question about the generated data,',
            '<gmt>       9       ! please contact mailto:yamaguti@alpha-net.ne.jp ',
            '<interval>  1       ! No.363, Tokyo, 東京(ﾄｳｷｮｳ)',
            '<firsttime> 1       ! Tokyo-To, 東京都(ﾄｳｷｮｳﾄ)',
            '<var>	IBEAM_H	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<var>	IBEAM_N	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<var>	IDIFF_H	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<var>	IGLOB_H	<col>	3  <interp> 0  <add>  0  <mult>  1   <samp>   0	! [W/m2]',
            '<var>	TAMB	<col>	1  <interp> 2  <add>  0  <mult>  1   <samp>   0	! [C]',
            '<var>	RHUM	<col>	2  <interp> 1  <add>  0  <mult>  1   <samp>   0	! [%]',
            '<var>	WSPEED	<col>	6  <interp> 1  <add>  0  <mult>  1   <samp>   0	! [m/s]',
            '<var>	WDIR	<col>	5  <interp> 1  <add>  0  <mult>  1   <samp>   0	! [deg.]',
            '<var>	udef1	<col>	4  <interp> 0  <add>  0  <mult>  1   <samp>   0	! Atmosphric radiation [W/m^2]',
            '<var>	udef2	<col>	7  <interp> 0  <add>  0  <mult>  1   <samp>   0	! Amount of rain [mm]',
            '<var>	udef3	<col>	8  <interp> 0  <add>  0  <mult>  1   <samp>   0	! Solar Radiation Time[hour]',
            '<var>	udef4	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<data>',
            ''
            ]

    #ヘッダーとデータをファイルへ出力
    with open(fname, mode='w', encoding='utf-8') as f:
        f.writelines('\n'.join(t99header))

    df.to_csv(fname, mode='a', header=False, index=False) #, float_format='%3.3f')


    