# coding: utf-8
# author     Yuichi Yasuda @ quattro corporate design
# copyright  quattro corporate design. All right reserved.


import weapy.wea2file as ea2
import weapy.epwfile as epw
import pandas as pd

if(__name__ == '__main__'):

    """例）拡張アメダス標準年のデータからTRNSYS,Type99形式のファイルを出力する
    """

    # 拡張アメダス気象データ
    # --------------------------------
    # weafile = r'F:\AMEDASTY.WEA' #1995年版
    # weafile = r'G:\EAD\RWY9100.WEA' #2000年版
    # weafile = r'D:\EAD\RWY0110.wea' #2010年版
    weafile = r'E:\EAD\PRY1120.wea2' #2020年版

    #地点
    no = 363        #東京
    # lat = 35.69     #緯度
    # lng = -139.76   #経度
    # elevation = 6.0 #標高

    # 拡張アメダス標準年データファイルの読み込み
    wea2 = ea2.Wea2File(weafile, no)

    # print(wea.ambient_temperatures)
    # print(wea.relative_humidities)
    
    # wea(WeaFileクラス）からDataFrameを生成する
    df = pd.DataFrame(
        {
        'TAMB': wea2.ambient_temperatures,
        'RHUM': wea2.relative_humidities,
        'IGLOB_H': wea2.horizontal_global_solar_irradiations,
        'udef1': wea2.downward_longwave_irradiations,
        'WDIR': wea2.wind_directions,
        'WSPEED': wea2.wind_velocities,
        'udef2': wea2.precipitation_amounts,
        'udef3': wea2.sunshine_durations,
        })

    # 有効数字を指定
    df = df.round({'TAMB':1, 'RHUM':3, 'IGLOB_H':3, 'udef1':3, 'WDIR':1, 'WSPEED':1, 'udef2':1, 'udef3':2})
    pd.options.display.float_format = '{:.4g}'.format

    # print(df)

    #ファイル名
    fname = 'ea2020_{0:0=3}_{1}.99'.format(no, wea2.station_roman_name)

    #Type99 のヘッダー（拡張アメダス気象データ、東京）
    t99header = [
            '<userdefined>       ! This weather data is generated by Weapy example. https://github.com/TRNSYSJP/weapy',
            '<longitude> {0} ! East of greenwich: negative'.format(wea2.longitude*(-1)),
            '<latitude>  {0}   ! '.format(wea2.latitude),
            '<gmt>       9       ! time shift from GMT, east: positive (hours)',
            '<interval>  1       ! Data file time interval between consecutive lines (hours)',
            '<firsttime> 1       ! Time corresponding to first data line (hours)',
            '<var>	IBEAM_H	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<var>	IBEAM_N	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<var>	IDIFF_H	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<var>	IGLOB_H	<col>	3  <interp> 0  <add>  0  <mult>  1   <samp>   0	! [W/m2]',
            '<var>	TAMB	<col>	1  <interp> 2  <add>  0  <mult>  1   <samp>   0	! [C]',
            '<var>	RHUM	<col>	2  <interp> 1  <add>  0  <mult>  1   <samp>   0	! [%]',
            '<var>	WSPEED	<col>	6  <interp> 1  <add>  0  <mult>  1   <samp>   0	! [m/s]',
            '<var>	WDIR	<col>	5  <interp> 1  <add>  0  <mult>  1   <samp>   0	! [deg.]',
            '<var>	udef1	<col>	4  <interp> 0  <add>  0  <mult>  1   <samp>   0	! Atmosphric radiation [W/m^2]',
            '<var>	udef2	<col>	7  <interp> 0  <add>  0  <mult>  1   <samp>   0	! Amount of rain [mm]',
            '<var>	udef3	<col>	8  <interp> 0  <add>  0  <mult>  1   <samp>   0	! Solar Radiation Time[hour]',
            '<var>	udef4	<col>	0  <interp> 0  <add>  0  <mult>  1   <samp>   0	!',
            '<data>',
            ''
            ]

    #ヘッダーとデータをファイルへ出力
    with open(fname, mode='w', encoding='utf-8') as f:
        f.writelines('\n'.join(t99header))

    df.to_csv(fname, mode='a', header=False, index=False, sep=' ') #, float_format='%3.3f')
    
    # デバッグ用に出力
    # df.to_csv(f'test_{wea2.station_roman_name}.csv', header=True, index=False, sep=',') #, float_format='%3.3f')
    


    